spring.application.name=score-event-processor
server.port=8080

spring.kafka.bootstrap-servers=localhost:9092
spring.data.mongodb.uri=mongodb://localhost:27017/points_table_database
spring.data.redis.host=localhost
spring.data.redis.port=6379

management.endpoints.web.exposure.include=health
