spring.application.name=scorekeeper
server.port=8081

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
key.serializer=org.apache.kafka.common.serialization.StringSerializer
value.serializer=com.cqrs.scorekeeper.kafka.serializer.UpdatePointsEventSerializer

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/points_table_database
spring.data.mongodb.auto-index-creation=true

# Feature flags
feature.cqrsmode=true

# Actuator
management.endpoints.web.exposure.include=health,info
