spring.application.name=table-retriever-service
spring.kafka.bootstrap-servers=localhost:9092
server.port=8083

# Batch settings
spring.kafka.consumer.properties.max.poll.records=3
spring.kafka.consumer.properties.max.poll.interval.ms=60000

# Redis settings
cache.enabled=true
spring.cache.type=redis
spring.redis.host=localhost
spring.redis.port=6379
# Cache expiration time in milliseconds
spring.cache.redis.time-to-live=60000
spring.redis.lettuce.pool.max-active=110
spring.redis.lettuce.pool.max-idle=25
spring.redis.lettuce.pool.min-idle=10
spring.redis.lettuce.pool.max-wait=1000ms
spring.redis.jedis.pool.max-active=110
spring.redis.jedis.pool.max-idle=10
spring.redis.jedis.pool.min-idle=5
spring.redis.jedis.pool.max-wait=1000ms